[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qoed"
version = "0.1.0"
description = "QOED is Quasi-Optimal Experimental Design"
requires-python = ">=3.10"
dependencies = [
  "matplotlib",
  "mujoco",
  "numpy",
  "torch==2.11.0",
  "torchvision==0.26.0",
]

[project.optional-dependencies]
mjlab = [
  "mjlab==1.6.0",
]

[project.scripts]
qoed-jackal-demo = "demos.jackal:main"
qoed-franka-demo = "demos.franka:main"

[tool.uv]
override-dependencies = ["rsl-rl-lib @ git+https://github.com/leggedrobotics/rsl_rl_rwm.git"]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.setuptools.packages.find]
include = ["boed*", "demos*", "mbpo*"]
